services:
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile

  storeservice:
    image: storeservice
    build:
      context: .
      dockerfile: StoreService/Dockerfile

  blazorapp1:
    image: blazorapp1
    build:
      context: .
      dockerfile: BlazorApp1/BlazorApp1/Dockerfile

  blazorapp1.client:
    image: blazorapp1.client
    build:
      context: .
      dockerfile: BlazorApp1/BlazorApp1.Client/Dockerfile

  gamewebapp:
    image: gamewebapp
    build:
      context: .
      dockerfile: GameWebApp/GameWebApp/Dockerfile

  gamewebapp.client:
    image: gamewebapp.client
    build:
      context: .
      dockerfile: GameWebApp/GameWebApp.Client/Dockerfile

