services:
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile

  storeservice:
    image: storeservice
    build:
      context: .
      dockerfile: StoreService/Dockerfile

